// 자동 생성 — scripts/generate-word-glosses.ts
// 한글 단어 → 영어 시각 설명 (이미지 생성 프롬프트용, 정확도 향상).
export const WORD_GLOSS: Record<string, string> = {
  "라면": "a bowl of instant noodles",
  "리본": "a pretty pink ribbon bow",
  "로봇": "a friendly shiny robot toy",
  "루돌프": "rudolph the red-nosed reindeer",
  "레몬": "a bright yellow lemon fruit",
  "리모컨": "a small black remote control",
  "라디오": "a vintage red radio player",
  "레고": "colorful plastic lego building blocks",
  "라켓": "a tennis racket and ball",
  "로켓": "a big red space rocket",
  "노래": "musical notes floating in air",
  "모래": "golden beach sand grains",
  "바람": "invisible wind blowing leaves",
  "사랑": "a big red heart shape",
  "다람쥐": "a cute fluffy squirrel eating nuts",
  "달리기": "a cute bunny running fast",
  "별": "a sparkling yellow star in sky",
  "달": "a crescent moon in night sky",
  "물": "clear blue flowing water",
  "말": "a friendly brown horse galloping",
  "하늘": "a bright blue sky with clouds",
  "물고기": "a colorful fish swimming in water",
  "얼음": "cold clear ice cubes",
  "날개": "a beautiful white bird wing",
  "달팽이": "a slow snail with a shell",
  "빨대": "a colorful drinking straw",
  "여름": "a bright sunny beach day",
  "겨울": "white snow falling on trees",
  "가을": "colorful leaves falling from trees",
  "팔": "a child's outstretched arm",
  "발": "a small bare human foot",
  "불": "a small warm campfire",
  "길": "a winding path through grass",
  "구름": "fluffy white clouds in sky",
  "이름": "a name tag on a shirt",
  "열매": "small red berries on a branch",
  "알람": "a ringing alarm clock",
  "공룡": "a friendly green dinosaur smiling",
  "풍선": "a colorful floating party balloon",
  "돌고래": "a happy blue dolphin jumping",
  "올챙이": "a small tadpole swimming in water",
  "파란색": "a bright blue color swatch",
  "노란색": "a bright yellow color swatch",
  "초록색": "a bright green color swatch",
  "빨간색": "a bright red color swatch",
  "수레": "a small wooden red wagon",
  "하루": "a bright sunny daytime scene",
  "마을": "a cozy little village with houses",
  "호루라기": "a small shiny silver whistle",
  "사자": "a friendly lion with a mane",
  "수박": "a big green watermelon",
  "소": "a cute brown cow",
  "새": "a small colorful bird",
  "사과": "a shiny red apple",
  "손": "a small child's hand",
  "시소": "a colorful playground seesaw",
  "사탕": "a sweet round candy",
  "소파": "a comfy living room sofa",
  "사슴": "a gentle brown deer",
  "사진": "a framed happy photo",
  "시장": "a bustling outdoor market",
  "소리": "a musical note symbol",
  "신발": "a pair of cute shoes",
  "선물": "a wrapped colorful present",
  "숟가락": "a shiny silver spoon",
  "솜사탕": "fluffy pink cotton candy",
  "소풍": "a happy family picnic",
  "식빵": "a soft white bread loaf",
  "상어": "a big blue shark",
  "시계": "a round wall clock",
  "소금": "white salt crystals",
  "수영": "a cute duck swimming",
  "수건": "a soft fluffy towel",
  "색연필": "a colorful drawing pencil",
  "선생님": "a kind smiling teacher",
  "수달": "a playful brown otter",
  "사다리": "a tall wooden ladder",
  "수족관": "a big fish aquarium",
  "스티커": "a shiny star sticker",
  "자동차": "a red toy car",
  "잠자리": "a colorful flying dragonfly",
  "지구": "a blue spinning earth globe",
  "주스": "a glass of orange juice",
  "자전거": "a red child's bicycle",
  "지우개": "a small pink eraser",
  "장난감": "a fun colorful toy",
  "조개": "a pretty ocean seashell",
  "젓가락": "a pair of chopsticks",
  "자석": "a strong horseshoe magnet",
  "지렁이": "a long pink earthworm",
  "집": "a cozy little house",
  "젤리": "a wobbly fruit jelly",
  "장갑": "a pair of warm gloves",
  "전화기": "an old red telephone",
  "지하철": "a fast moving subway train",
  "저금통": "a cute pink piggy bank",
  "자장가": "a sleeping baby's face",
  "지팡이": "a brown wooden walking stick",
  "재미": "a happy smiling face",
  "재채기": "a cute bunny sneezing",
  "조각": "a small piece of cake",
  "지갑": "a small colorful wallet",
  "주머니": "a small fabric pouch",
  "진달래": "a pink azalea flower",
  "차": "a cute red car",
  "채소": "a colorful fresh vegetable",
  "치킨": "a crispy fried chicken",
  "초콜릿": "a delicious brown chocolate bar",
  "축구": "a soccer ball on grass",
  "책": "a colorful open book",
  "침대": "a cozy soft bed",
  "창문": "a clear glass window",
  "참새": "a small brown sparrow bird",
  "청소기": "a cute robot vacuum cleaner",
  "치약": "a tube of toothpaste",
  "촛불": "a flickering candle flame",
  "치즈": "a yellow block of cheese",
  "춤": "a cute animal dancing happily",
  "철봉": "a metal horizontal bar",
  "천둥": "a dark cloud with lightning",
  "청개구리": "a small green tree frog",
  "고양이": "a fluffy cute cat",
  "곰": "a big brown bear",
  "기차": "a long colorful train",
  "가방": "a small colorful bag",
  "강아지": "a playful cute puppy",
  "기린": "a tall spotted giraffe",
  "거미": "a small black spider",
  "개구리": "a green jumping frog",
  "귤": "a round orange tangerine",
  "그네": "a wooden playground swing",
  "가위": "a pair of colorful scissors",
  "거울": "a shiny silver mirror",
  "고구마": "a purple sweet potato",
  "감자": "a brown round potato",
  "게": "a red ocean crab",
  "거북이": "a slow green turtle",
  "공": "a colorful bouncy ball",
  "고래": "a big blue whale",
  "고릴라": "a strong black gorilla",
  "가지": "a long purple eggplant",
  "국수": "a bowl of noodles",
  "귀": "a cute animal ear",
  "극장": "a big movie theater",
  "나비": "a colorful flying butterfly",
  "눈": "white falling snow flakes",
  "냉장고": "a big white refrigerator",
  "나무": "a tall green tree",
  "냄비": "a round cooking pot",
  "나팔": "a shiny golden trumpet",
  "낙타": "a brown desert camel",
  "놀이터": "a colorful outdoor playground",
  "눈물": "a tiny blue tear drop",
  "나물": "green leafy vegetables",
  "낮잠": "a sleepy fox napping",
  "노트": "a small blank notebook",
  "누나": "a kind older sister",
  "낙엽": "colorful fallen autumn leaves",
  "너구리": "a cute striped raccoon",
  "냉면": "a bowl of cold noodles",
  "노루": "a small brown roe deer",
  "무지개": "a bright arching rainbow",
  "도토리": "a tiny brown acorn",
  "딸기": "a juicy red strawberry",
  "당근": "a crunchy orange carrot",
  "돼지": "a happy pink pig",
  "동생": "a playful younger sibling",
  "도넛": "a sweet glazed donut",
  "달걀": "a white oval egg",
  "도서관": "a cozy book filled library",
  "다리": "a long stone bridge",
  "도마뱀": "a small green lizard",
  "독수리": "a majestic flying eagle",
  "도화지": "a blank white drawing paper",
  "두더지": "a tiny digging mole",
  "도깨비": "a playful korean goblin",
  "달고나": "a sweet dalgona candy",
  "대나무": "tall green bamboo stalks",
  "두루미": "a graceful white crane",
  "바나나": "a yellow peeled banana",
  "버스": "a big yellow school bus",
  "병아리": "a fluffy yellow chick",
  "별빛": "twinkling night starlight",
  "부엉이": "a wise brown owl",
  "버섯": "a red spotted mushroom",
  "바다": "a wide blue ocean",
  "배": "a small wooden boat",
  "봄": "colorful spring flowers blooming",
  "번개": "a bright zig-zag lightning",
  "바위": "a large gray rock",
  "배추": "a green napa cabbage",
  "비행기": "a big flying airplane",
  "반딧불이": "a glowing tiny firefly",
  "빗자루": "a wooden straw broom",
  "병원": "a friendly white hospital",
  "불꽃": "colorful bursting fireworks",
  "빵": "a warm brown bread",
  "마트": "a busy grocery mart",
  "모자": "a cute colorful hat",
  "문어": "a friendly red octopus",
  "미끄럼틀": "a colorful playground slide",
  "메뚜기": "a green jumping grasshopper",
  "목도리": "a warm knitted scarf",
  "물감": "colorful paint tubes",
  "마이크": "a shiny singing microphone",
  "망원경": "a big stargazing telescope",
  "만두": "steaming yummy dumplings",
  "매미": "a noisy tree cicada",
  "모기": "a tiny buzzing mosquito",
  "먹구름": "dark stormy rain clouds",
  "무당벌레": "a red spotted ladybug",
  "메론": "a sweet green melon",
  "망고": "a juicy yellow mango",
  "마스크": "a cute animal face mask",
  "모래성": "a tall beach sandcastle",
  "하마": "a big swimming hippo",
  "호랑이": "a striped roaring tiger",
  "화분": "a small flower pot",
  "해": "a bright yellow sun",
  "호박": "a round orange pumpkin",
  "해바라기": "a tall yellow sunflower",
  "헬리콥터": "a flying red helicopter",
  "호떡": "a warm sweet pancake",
  "해파리": "a floating colorful jellyfish",
  "학교": "a happy school building",
  "호수": "a calm blue lake",
  "하품": "a sleepy yawning puppy",
  "허수아비": "a friendly straw scarecrow",
  "화장실": "a clean toilet room",
  "흙": "dark brown garden soil",
  "토끼": "a fluffy white bunny",
  "타조": "a tall running ostrich",
  "태양": "a big shining sun",
  "토마토": "a round red tomato",
  "트럭": "a big delivery truck",
  "터널": "a dark long tunnel",
  "탱크": "a big green tank",
  "태풍": "a swirling stormy typhoon",
  "턱": "a cute baby's chin",
  "텔레비전": "a colorful tv screen",
  "튀김": "crispy golden fried food",
  "탑": "a tall stone tower",
  "택시": "a yellow city taxi",
  "파도": "a big ocean wave",
  "파인애플": "a spiky yellow pineapple",
  "포도": "a bunch of grapes",
  "피자": "a cheesy pepperoni pizza",
  "팽이": "a colorful spinning top",
  "피리": "a small wooden flute",
  "편지": "a sealed love letter",
  "폭포": "a tall gushing waterfall",
  "팝콘": "fluffy white popcorn kernels",
  "펭귄": "a cute waddling penguin",
  "피아노": "a black grand piano",
  "표범": "a spotted jungle leopard",
  "꽃": "a colorful blooming flower",
  "꿀벌": "a fuzzy yellow honeybee",
  "꿈": "a sleeping child dreaming",
  "깃발": "a waving colorful flag",
  "끈": "a long tangled string",
  "떡볶이": "spicy red tteokbokki dish",
  "뚜껑": "a round pot lid",
  "떡국": "a warm rice cake soup",
  "딸기잼": "sweet red strawberry jam",
  "빨래": "colorful clothes on a line",
  "뿌리": "underground plant roots",
  "씨앗": "a tiny brown seed",
  "쓰레기통": "a full metal trash can",
  "썰매": "a red wooden sled",
  "찌개": "a bubbling hot stew",
  "쪽지": "a small written note",
  "찐만두": "fluffy white steamed dumplings",
  "엄마": "a kind smiling mother",
  "아빠": "a strong happy father",
  "할머니": "a sweet smiling grandmother",
  "할아버지": "a wise smiling grandfather",
  "언니": "a kind older sister",
  "오빠": "a playful older brother",
  "형": "a strong older brother",
  "눈코입": "a happy face eyes nose mouth",
  "무릎": "a bent human knee",
  "머리": "a child's soft hair",
  "배꼽": "a tiny round belly button",
  "밥": "a bowl of white rice",
  "국": "a warm steaming soup",
  "우유": "a glass of white milk",
  "과자": "a crunchy sweet cookie",
  "사탕수수": "tall green sugarcane stalks",
  "케이크": "a colorful birthday cake",
  "아이스크림": "a melting ice cream cone",
  "꽃잎": "a delicate flower petal",
  "비": "gentle falling raindrops",
  "눈사람": "a happy smiling snowman",
  "바닷가": "a sunny sandy beach",
  "폭풍": "a dark stormy sky",
  "새싹": "a tiny green sprout",
  "솔방울": "a brown bumpy pinecone",
  "단풍": "colorful autumn leaves falling",
  "블록": "colorful building blocks",
  "인형": "a cute cuddly doll",
  "퍼즐": "a colorful jigsaw puzzle",
  "색종이": "colorful paper sheets",
  "크레파스": "colorful wax crayons",
  "수영복": "a child's swimming suit",
  "줄넘기": "a child jumping rope",
  "미술": "a child painting art",
  "의사": "a friendly doctor",
  "경찰관": "a friendly police officer",
  "소방관": "a friendly firefighter",
  "교사": "a kind teacher",
  "농부": "a farmer in a field",
  "요리사": "a chef cooking food",
  "의사선생님": "a friendly doctor",
  "우체부": "a mail carrier delivering letters",
  "경찰": "a friendly police officer",
  "화가": "an artist painting a picture",
  "음악가": "a musician playing an instrument",
  "운동선수": "an athlete running fast",
  "선수": "an athlete running fast",
  "야구": "a child playing baseball",
  "탁구": "a child playing table tennis",
  "배드민턴": "a child playing badminton",
  "스키": "a child skiing down a mountain",
  "스케이트": "a child ice skating",
  "멀리뛰기": "a child long jumping",
  "높이뛰기": "a child high jumping",
  "체조": "a child doing gymnastics",
  "무술": "a child doing martial arts",
  "태권도": "a child doing taekwondo",
  "행복": "a happy smiling face",
  "슬픔": "a sad crying face",
  "화남": "an angry frowning face",
  "무서움": "a scared wide-eyed face",
  "신남": "an excited jumping face",
  "졸음": "a sleepy yawning face",
  "피로": "a tired droopy face",
  "부끄러움": "a shy blushing face",
  "설렘": "an excited anticipating face",
  "얼룩말": "a striped black and white zebra",
  "코끼리": "a big gray elephant",
  "캥거루": "a jumping kangaroo with joey",
  "오랑우탄": "a red-haired orangutan",
  "침팬지": "a playful chimpanzee",
  "들소": "a big hairy bison",
  "라마": "a fluffy llama",
  "양": "a fluffy white sheep",
  "염소": "a cute goat",
  "사슴벌레": "a stag beetle",
  "나방": "a colorful moth",
  "매": "a majestic flying hawk",
  "악어": "a green alligator smiling",
  "개미": "a tiny black ant walking",
  "나뭇잎": "a green leaf falling",
  "소시지": "a grilled sausage link",
  "비빔밥": "a colorful mixed rice bowl",
  "김밥": "a seaweed rice roll slice",
  "우동": "a warm noodle soup bowl",
  "스파게티": "a plate of red spaghetti",
  "카레": "a yellow curry bowl",
  "핫도그": "a hot dog with mustard",
  "케첩": "a red ketchup bottle",
  "마요네즈": "a white mayonnaise jar",
  "기름": "a bottle of cooking oil",
  "설탕": "a pile of white sugar",
  "요구르트": "a small yogurt cup",
  "버터": "a yellow stick of butter",
  "잼": "a jar of fruit jam",
  "누텔라": "a jar of chocolate spread",
  "두유": "a carton of soy milk",
  "머리카락": "long brown wavy hair",
  "이마": "a smooth forehead skin",
  "눈썹": "a curved eyebrow arch",
  "코": "a small round nose",
  "입술": "red smiling lips",
  "이빨": "tiny white teeth showing",
  "혀": "a pink tongue sticking out",
  "목": "a short neck",
  "어깨": "a round shoulder",
  "팔꿈치": "a bent elbow joint",
  "손가락": "five small fingers",
  "가슴": "a soft chest area",
  "엉덩이": "a round bottom",
  "정강이": "a lower leg bone",
  "발목": "a small ankle joint",
  "발톱": "a tiny toenail",
  "근육": "strong arm muscles",
  "뼈": "a white bone structure",
  "뇌": "a pink brain inside head",
  "셔츠": "a blue t-shirt",
  "바지": "a pair of blue pants",
  "속옷": "a pair of white underwear",
  "양말": "a striped sock pair",
  "부츠": "a pair of brown boots",
  "운동화": "a pair of colorful sneakers",
  "슬리퍼": "a soft house slipper",
  "내복": "a warm pajama set",
  "스웨터": "a cozy knitted sweater",
  "코트": "a warm winter coat",
  "웃다": "a cute fox laughing",
  "울다": "a cute bear crying",
  "걷다": "a cute bear walking",
  "앉다": "a cute cat sitting down",
  "누우다": "a cute puppy lying down",
  "일어나다": "a cute chick standing up",
  "자다": "a cute fox sleeping soundly",
  "먹다": "a cute bunny eating carrots",
  "마시다": "a cute squirrel drinking water",
  "보다": "a cute owl looking around",
  "듣다": "a cute dog listening carefully",
  "말하다": "a cute bird talking happily",
  "쓰다": "a cute monkey writing a letter",
  "읽다": "a cute mouse reading a book",
  "그리다": "a cute elephant drawing a picture",
  "만들다": "a cute beaver building something",
  "찾다": "a cute detective searching for clues",
  "숨다": "a cute chameleon hiding quietly",
  "밀다": "a cute bear pushing a box",
  "당기다": "a cute dog pulling a rope",
  "뜨겁다": "a steaming hot cup",
  "차갑다": "a frosty cold ice cube",
  "빠르다": "a speedy cheetah running fast",
  "느리다": "a slow snail crawling along",
  "어둡다": "a dark night sky",
  "깨끗하다": "a sparkling clean shiny surface",
  "더럽다": "a muddy messy dirty puddle",
  "단맛": "a sweet candy lollipop",
  "짠맛": "a salty ocean wave",
  "책상": "a wooden school desk",
  "의자": "a small comfy chair",
  "칠판": "a big green blackboard",
  "딱지": "a colorful paper flipping game",
  "그림책": "a colorful story picture book",
  "교실": "a bright school classroom",
  "운동장": "a green outdoor playground",
  "급식실": "a busy school cafeteria",
  "빨강": "a bright red apple",
  "파랑": "a deep blue ocean",
  "노랑": "a sunny yellow flower",
  "초록": "a vibrant green leaf",
  "보라": "a beautiful purple grape",
  "분홍": "a soft pink flower",
  "회색": "a cloudy gray sky",
  "검정": "a dark black night",
  "하양": "a fluffy white cloud",
  "주황": "a juicy orange fruit",
  "날씨": "a sunny cloudy rainy day",
  "맑음": "a clear blue sky",
  "흐림": "a gray cloudy sky",
  "햇빛": "a warm bright sunbeam",
  "오토바이": "a fast motorcycle driving by",
  "스쿠터": "a small blue scooter",
  "참외": "a yellow striped melon",
  "복숭아": "a fuzzy pink peach",
  "체리": "two shiny red cherries",
  "라임": "a small green lime",
  "귀리": "a bowl of oats",
  "무화과": "a purple fig cut open",
  "옥수수": "a yellow ear of corn",
  "양파": "a round purple onion",
  "마늘": "a white garlic bulb",
  "상추": "a green leafy lettuce",
  "오이": "a long green cucumber",
  "침실": "a cozy bed with pillows",
  "거실": "a comfy sofa and rug",
  "주방": "a bright kitchen counter",
  "욕실": "a bubbly bathtub and duck",
  "현관": "a welcome mat at door",
  "베란다": "a sunny balcony with plants",
  "복도": "a long empty hallway",
  "계단": "a winding wooden staircase",
  "엘리베이터": "a shiny metal elevator door",
  "뛰다": "a cute bunny running fast",
  "점프": "a cute frog jumping high",
  "기다리다": "a cute puppy waiting patiently",
  "어기다": "a cute kitten making a mess",
  "미끄러지다": "a cute penguin sliding down",
  "비틀다": "a cute monkey twisting a rope",
  "세우다": "a cute dog standing tall",
  "누르다": "a cute bear pressing a button",
  "친구": "two happy children holding hands",
  "아주머니": "a kind smiling woman",
  "아저씨": "a friendly smiling man",
  "기타": "a small brown guitar",
  "드럼": "a red drum set",
  "바이올린": "a shiny brown violin",
  "플루트": "a silver musical flute",
  "트롬본": "a long brass trombone",
  "마라카스": "two colorful maracas shaking",
  "실로폰": "a colorful wooden xylophone",
  "종": "a small golden bell",
  "탬버린": "a round jingly tambourine",
  "보드게임": "a colorful board game pieces",
  "주사위": "a red dice rolling",
  "카드": "a stack of playing cards",
  "연": "a colorful kite flying high",
  "동화": "an open storybook magic",
  "만화": "a funny cartoon character smiling",
  "글자": "colorful alphabet letters blocks",
  "그림": "a child's colorful drawing",
  "색칠": "a child coloring a picture",
  "이야기": "a colorful open storybook",
  "페이지": "a white paper page",
  "표지": "a colorful book cover",
  "잉크": "a spilled black ink bottle",
  "계란": "a yellow egg yolk",
  "밀가루": "a white flour bag",
  "간장": "a brown soy sauce bottle",
  "고추장": "a red gochujang paste jar",
  "된장": "a brown doenjang paste jar",
  "봄날": "a sunny spring flower field",
  "여름방학": "kids playing on a beach",
  "개학": "a school bus arriving",
  "방학": "a happy child playing",
  "명절": "a family celebrating together",
  "정월": "a new year celebration",
  "간식": "a plate of yummy cookies",
  "반찬": "small colorful food dishes",
  "국물": "a warm soup bowl",
  "끼니": "a family eating dinner",
  "식탁": "a wooden dining table",
  "연필": "a yellow wooden pencil",
  "펜": "a blue ink pen",
  "자": "a long wooden ruler",
  "풀": "a blue glue stick",
  "깍지": "a small pen cap",
  "스템프": "a red rubber stamp",
  "테이프": "a clear adhesive tape roll",
  "베개": "a soft fluffy pillow",
  "매트리스": "a comfy bed mattress",
  "빗": "a pink hair comb",
  "타올": "a soft white towel",
  "휴지": "a roll of toilet paper",
  "걸레": "a wet cleaning rag",
  "안녕": "a friendly waving hand",
  "고마워": "a grateful smiling face",
  "미안해": "a sad apologetic face",
  "괜찮아": "a reassuring gentle smile",
  "좋아": "a happy thumbs up",
  "싫어": "a frowning unhappy face",
  "아니오": "a shaking head gesture",
  "축하해": "a celebratory party popper",
  "낮": "a bright sunny sky",
  "밤": "a dark starry night",
  "시간": "a ticking clock face",
  "분": "a clock's minute hand",
  "초": "a clock's second hand",
  "위": "an arrow pointing upwards",
  "아래": "an arrow pointing downwards",
  "앞": "a person facing forward",
  "뒤": "a person facing backward",
  "옆": "a cute cat next to a box",
  "안": "a cute bear inside a box",
  "밖": "a cute dog outside a house",
  "오른쪽": "a cute bird on the right",
  "왼쪽": "a cute bird on the left",
  "중간": "a cute fox in the middle",
  "내 것": "a cute puppy holding its toy",
  "너 것": "a cute puppy giving a toy",
  "물건": "a colorful toy block",
  "상자": "a brown cardboard box",
  "도구": "a small red hammer",
  "먼지": "tiny grey dust particles",
  "생일": "a birthday cake with candles",
  "파티": "colorful balloons and confetti",
  "초대": "a cute invitation card",
  "축제": "colorful flags and fireworks",
  "졸업": "a cute animal wearing a cap",
  "운동회": "cute animals running a race",
  "발표": "a cute animal speaking on stage",
  "경쟁": "two cute animals racing",
  "게임": "cute animals playing a board game",
  "꼬리": "a fluffy fox tail",
  "껌": "a pink bubble gum",
  "꼭": "a cute animal holding tight",
  "꿀": "a jar of golden honey",
  "꼬마": "a small cute child",
  "꼬치": "meat and vegetables on a skewer",
  "꽈배기": "a sweet twisted donut",
  "꿩": "a colorful pheasant bird",
  "떡": "soft white rice cakes",
  "똥": "a small brown poop",
  "딱따구리": "a cute woodpecker pecking wood",
  "따뜻해": "a cute animal feeling warm",
  "땅콩": "a brown peanut shell",
  "딸꾹질": "a cute animal hiccuping",
  "뽀로로": "a cute blue penguin character",
  "뻐꾸기": "a cute cuckoo bird",
  "빼기": "a cute animal taking away blocks",
  "빨리": "a cute bunny running fast",
  "빵집": "a cute bakery shop",
  "뽑기": "a toy vending machine",
  "뻥튀기": "a pile of puffed rice",
  "쌀": "a bowl of white rice",
  "쓰레기": "a pile of colorful trash",
  "씻어": "a cute animal washing hands",
  "쌓다": "a cute animal stacking blocks",
  "씩씩해": "a brave smiling face",
  "쓰다듬어": "a cute animal petting a puppy",
  "짜다": "a cute animal squeezing a tube",
  "쪼개": "a cute animal splitting a cookie",
  "찐빵": "a warm fluffy steamed bun",
  "짱구": "a mischievous boy with big eyebrows",
  "쫄깃": "a chewy mochi rice cake",
  "쪽": "a cute bunny giving a kiss",
  "쫑긋": "a bunny with perked up ears",
  "리코더": "a small brown recorder flute",
  "롤케이크": "a swirly cream roll cake",
  "리듬": "a dancing animal moving to rhythm",
  "롤러스케이트": "colorful roller skates with wheels",
  "쇼핑": "a bear pushing a shopping cart",
  "세수": "a puppy washing its face",
  "슬라임": "stretchy colorful gooey slime",
  "수영장": "a blue water swimming pool",
  "서랍": "a wooden drawer pulled open",
  "손수건": "a small patterned handkerchief",
  "청소": "a squirrel sweeping the floor",
  "초코": "a delicious brown chocolate bar",
  "추석": "a family celebrating chuseok harvest festival",
  "고슴도치": "a cute spiky hedgehog",
  "곤충": "a small green crawling insect",
  "금붕어": "a shiny orange goldfish swimming",
  "기차역": "a bustling train station platform",
  "강낭콩": "a green bean pod",
  "달력": "a wall calendar with dates",
  "도시락": "a bento box lunchbox",
  "동화책": "an open colorful storybook",
  "도너츠": "a round sweet glazed donut",
  "번데기": "a silkworm pupa cocoon",
  "보물섬": "a map to a treasure island",
  "봄바람": "a gentle spring breeze blowing",
  "벌레": "a tiny crawling ladybug",
  "볶음밥": "a bowl of fried rice",
  "보라색": "a vibrant purple color swatch",
  "미로": "a winding green garden maze",
  "마카롱": "colorful round french macarons",
  "호두": "a hard brown walnut shell",
  "향기": "a flower emitting sweet fragrance",
  "포크": "a shiny silver eating fork",
  "풍선껌": "a pink bubble gum bubble",
  "트램폴린": "a bouncy round trampoline",
  "찰싹": "a puppy patting a friend",
  "붓": "a paint brush with bristles",
  "찰흙": "a lump of soft brown clay",
  "스케치북": "an open blank sketchbook",
  "책가방": "a colorful school backpack",
  "알림장": "a school notice communication book",
  "소나기": "a sudden short rain shower",
  "안개": "a thick white misty fog",
  "홍학": "a tall pink flamingo bird",
  "카멜레온": "a colorful chameleon on a branch",
  "코알라": "a cute koala bear",
  "판다": "a cute panda bear",
  "미어캣": "a cute meerkat standing up",
  "올빼미": "a cute owl with big eyes",
  "불가사리": "a colorful starfish on sand",
  "홍합": "a purple mussel shell",
  "가오리": "a cute stingray swimming",
  "쥐": "a cute little mouse",
  "토끼풀": "green clover leaves",
  "장수풍뎅이": "a shiny rhinoceros beetle",
  "순대": "sliced korean blood sausage",
  "잡채": "colorful glass noodles with vegetables",
  "된장찌개": "a bubbling soybean paste stew",
  "삼겹살": "grilled pork belly slices",
  "삼계탕": "a whole chicken soup",
  "갈비": "grilled short ribs",
  "감자튀김": "golden french fries",
  "햄버거": "a big juicy hamburger",
  "쿠키": "a chocolate chip cookie",
  "삶은달걀": "a peeled boiled egg",
  "군고구마": "a roasted sweet potato",
  "붕어빵": "a fish shaped pastry",
  "타코야끼": "round octopus balls",
  "오징어볶음": "spicy stir fried squid",
  "소방차": "a big red fire truck",
  "구급차": "a white ambulance car",
  "경찰차": "a black and white police car",
  "굴착기": "a yellow excavator digging",
  "기중기": "a tall crane lifting",
  "잠수함": "a yellow submarine underwater",
  "우주선": "a rocket spaceship flying",
  "케이블카": "a cable car in mountains",
  "킥보드": "a child riding a scooter",
  "속눈썹": "long dark eyelashes",
  "볼": "a rosy cheek",
  "뒤통수": "the back of a head",
  "겨드랑이": "an armpit area",
  "손톱": "a small fingernail",
  "발뒤꿈치": "a human heel",
  "갈비뼈": "white rib bones",
  "척추": "a human spine bone",
  "장롱": "a wooden wardrobe closet",
  "세탁기": "a white washing machine",
  "전자레인지": "a microwave oven",
  "가스레인지": "a kitchen gas stove",
  "커튼": "a colorful window curtain",
  "이불": "a soft warm blanket",
  "선풍기": "a standing electric fan",
  "에어컨": "a white air conditioner",
  "수도꼭지": "a shiny water faucet",
  "농구": "a round orange basketball",
  "배구": "a white and blue volleyball",
  "볼링": "a shiny bowling ball and pins",
  "훌라후프": "a colorful plastic hula hoop",
  "평행봉": "two long parallel bars",
  "간호사": "a kind nurse in uniform",
  "조종사": "a pilot flying an airplane",
  "우주인": "an astronaut in a space suit",
  "분홍색": "a soft pink color swatch",
  "주황색": "a bright orange color swatch",
  "갈색": "a warm brown color swatch",
  "하늘색": "a light sky blue color swatch",
  "금색": "a shimmering gold color swatch",
  "은색": "a shiny silver color swatch",
  "연두색": "a fresh light green color swatch",
  "자주색": "a deep purple color swatch",
  "살구색": "a soft apricot color swatch",
  "베이지": "a calm beige color swatch",
  "더하기": "a plus sign for adding",
  "달콤해": "a happy face eating candy",
  "쓰디써": "a puckered face tasting something bitter",
  "새콤해": "a scrunched face tasting something sour",
  "짭짤해": "a smiling face eating salty chips",
  "고소해": "a happy face smelling roasted nuts",
  "뜨거워": "steam rising from a cup",
  "차가워": "ice cubes in a glass",
  "부드러워": "a fluffy white cloud",
  "거칠어": "a bumpy rough rock surface",
  "미끄러워": "a cute penguin slipping on ice",
  "설레어": "a wide eyed excited face",
  "창피해": "a blushing red embarrassed face",
  "부러워": "a longing look on a face",
  "티셔츠": "a colorful short sleeved t-shirt",
  "치마": "a pretty flowing skirt",
  "조끼": "a warm button up vest",
  "잠옷": "soft comfy pajamas with patterns",
  "구두": "shiny dress shoes with laces",
  "박물관": "a grand building with exhibits",
  "미술관": "a building filled with paintings",
  "놀이공원": "a fun park with rides",
  "편의점": "a small store with snacks",
  "약국": "a store with medicine bottles",
  "우체국": "a building with mailboxes",
  "은행": "a secure building with money",
  "공항": "a big building with airplanes",
  "항구": "a busy port with ships",
  "돌멩이": "a small smooth grey pebble",
  "산봉우리": "a tall pointy mountain peak",
  "계곡": "a green valley with a river",
  "사막": "a vast sandy desert with cacti",
  "열대우림": "tropical rainforest with animals",
  "빙하": "giant blue ice glacier",
  "민들레": "fluffy yellow dandelion flower",
  "튤립": "colorful tulip flower field",
  "장미": "beautiful red rose flower",
  "벚꽃": "pink cherry blossom tree",
  "코스모스": "tall pink cosmos flower",
  "수선화": "yellow daffodil flower bloom",
  "선인장": "green spiky cactus plant",
  "이끼": "soft green moss patch",
  "단풍잎": "red autumn maple leaf",
  "소나무": "tall green pine tree",
  "느티나무": "large green zelkova tree",
  "넝쿨": "green climbing vine plant",
  "홍수": "big flood water rising",
  "가뭄": "dry cracked earth ground",
  "눈보라": "swirling white snow blizzard",
  "비구름": "dark rain cloud pouring",
  "황사": "yellow dust storm blowing",
  "결빙": "thin ice on water",
  "화성": "red planet mars surface",
  "목성": "giant striped jupiter planet",
  "토성": "ringed saturn planet in space",
  "혜성": "bright comet with tail",
  "은하수": "sparkling milky way galaxy",
  "전기": "bright yellow lightning bolt",
  "실험": "a scientist doing experiment",
  "돋보기": "a magnifying glass looking",
  "첼로": "a brown cello instrument",
  "트럼펫": "a shiny golden trumpet",
  "심벌즈": "two round cymbals clashing",
  "하모니카": "a small harmonica instrument",
  "북": "a big drum instrument",
  "종이접기": "colorful paper origami art",
  "꼴라주": "a paper collage artwork",
  "도자기": "a handmade clay pot",
  "스텐실": "a stencil art pattern",
  "뜨개질": "knitting colorful yarn wool",
  "자수": "embroidered flower on fabric",
  "비즈공예": "colorful bead craft art",
  "목공예": "carved wooden animal craft",
  "두드려": "a cute bear tapping",
  "굴려": "a cute puppy rolling",
  "던져": "a cute monkey throwing",
  "받아": "a cute squirrel catching",
  "당겨": "a cute kitten pulling",
  "돌려": "a cute mouse spinning",
  "흔들어": "a cute bunny shaking",
  "구부려": "a cute fox bending",
  "접어": "a cute bird folding",
  "끼워": "a cute bear inserting a block",
  "빠져": "a cute fox falling out",
  "올라가": "a cute monkey climbing up",
  "내려가": "a cute squirrel going down",
  "건너": "a cute duck crossing a bridge",
  "통과해": "a cute mouse passing through a hole",
  "무겁다": "a cute elephant lifting heavy box",
  "가볍다": "a cute bird holding light feather",
  "많다": "many colorful balloons floating",
  "적다": "a few small candies",
  "감사해": "a happy smiling face with thanks",
  "죄송해": "a sad apologetic face",
  "실례해": "a cute bunny politely asking",
  "기다려": "a cute dog waiting patiently",
  "도와줘": "a cute kitten asking for help",
  "함께해": "cute friends playing together",
  "배려해": "a cute bear sharing toys",
  "양치질": "a cute bear brushing teeth",
  "손발씻기": "a cute monkey washing hands feet",
  "샤워": "a cute duck taking a shower",
  "목욕": "a cute puppy taking a bath",
  "비누": "a bubbly bar of soap",
  "체온계": "a small red thermometer",
  "반창고": "a colorful cartoon band-aid",
  "주사": "a small medical syringe",
  "약": "colorful small medicine pills",
  "기침": "a cute fox coughing softly",
  "벚꽃놀이": "friends viewing pink cherry blossoms",
  "단풍구경": "friends viewing colorful autumn leaves",
  "낙엽밟기": "a cute squirrel stepping on leaves",
  "썰매타기": "a cute bear sledding downhill",
  "눈싸움": "cute friends having a snowball fight",
  "모래놀이": "cute children playing in sand",
  "마법사": "a friendly wizard with a hat",
  "용": "a friendly green dragon flying",
  "요정": "a tiny sparkling fairy flying",
  "마녀": "a friendly witch on broomstick",
  "왕자": "a handsome prince with a crown",
  "공주": "a beautiful princess with a crown",
  "기사": "a brave knight in armor",
  "거인": "a friendly giant smiling big",
  "난쟁이": "a small dwarf with a pickaxe",
  "보물": "a sparkling treasure chest gold",
  "성": "a tall majestic stone castle",
  "성곽": "strong stone castle walls",
  "일어나기": "a cute bear waking up",
  "세수하기": "a cute bunny washing its face",
  "밥먹기": "a cute puppy eating food",
  "가방싸기": "a cute fox packing a backpack",
  "등교하기": "a cute bear going to school",
  "하교하기": "children walking home from school",
  "숙제하기": "a child doing homework at a desk",
  "잠자기": "a cute bear sleeping in bed",
  "한복": "colorful traditional korean clothing",
  "태극기": "the korean national flag",
  "김치": "spicy red korean kimchi",
  "한옥": "a beautiful traditional korean house",
  "기와": "curved traditional korean roof tiles",
  "장구": "a traditional korean hourglass drum",
  "가야금": "a traditional korean string instrument",
  "탈춤": "people dancing with korean masks",
  "부채": "a beautiful korean hand fan",
  "연날리기": "a child flying a colorful kite",
  "윷놀이": "children playing a korean board game",
  "제기차기": "a child kicking a shuttlecock",
  "씨름": "two strong men wrestling",
  "설날": "a family celebrating korean new year",
  "송편": "colorful half-moon shaped rice cakes",
  "불고기": "delicious grilled korean beef",
  "순두부": "a bowl of soft tofu stew",
  "칼국수": "a bowl of korean noodles",
  "된장국": "a bowl of korean soybean soup",
  "오믈렛": "a fluffy yellow omelet",
  "샌드위치": "a tasty layered sandwich",
  "공작새": "a beautiful peacock with feathers",
  "플라밍고": "a tall pink flamingo bird",
  "까치": "a black and white magpie bird",
  "제비": "a small black swallow bird",
  "박쥐": "a cute brown flying bat",
  "오소리": "a striped black and white badger",
  "해마": "a tiny orange seahorse swimming",
  "복어": "a round spiky pufferfish",
  "뱀장어": "a long slippery green eel",
  "전갈": "a scary brown scorpion",
  "타란툴라": "a big hairy spider tarantula",
  "이구아나": "a green lizard iguana",
  "알파카": "a fluffy white alpaca",
  "재규어": "a spotted jungle jaguar",
  "치타": "a fast spotted cheetah",
  "망고새": "a colorful bird eating mango",
  "왜가리": "a tall grey heron bird",
  "수의사": "a doctor helping sick animals",
  "약사": "a person giving out medicine",
  "건축가": "a person designing buildings",
  "작가": "a person writing a book",
  "기자": "a person reporting news",
  "파일럿": "a pilot flying an airplane",
  "선장": "a captain steering a ship",
  "우주비행사": "an astronaut floating in space",
  "테니스": "a child playing tennis",
  "골프": "a golf club and ball",
  "권투": "boxing gloves and ring",
  "유도": "two kids doing judo",
  "스케이팅": "a child ice skating",
  "서핑": "a surfer on a wave",
  "사이클": "a child riding a bicycle",
  "마라톤": "children running a race",
  "양궁": "a child shooting an arrow",
  "펜싱": "two children fencing",
  "역도": "a strong child lifting weights",
  "버스터미널": "a busy bus station",
  "등대": "a tall bright lighthouse",
  "식물원": "a garden with many plants",
  "캠핑장": "a tent in a forest",
  "동굴": "a dark rocky cave",
  "절": "a traditional korean temple",
  "교회": "a church with a steeple",
  "백화점": "a big shopping building",
  "세탁소": "a washing machine and clothes",
  "컴퓨터": "a desktop computer screen",
  "태블릿": "a small tablet device",
  "스마트폰": "a child holding a phone",
  "충전기": "a phone charging cable",
  "이어폰": "small white earphones",
  "카메라": "a camera taking a picture",
  "드론": "a flying drone toy",
  "프린터": "a printer making paper",
  "키보드": "a computer keyboard with keys",
  "마우스": "a computer mouse device",
  "이메일": "an envelope with an email symbol",
  "인터넷": "a globe with connection lines",
  "게임기": "a video game controller",
  "가운데": "a dot in the middle",
  "사이": "a small object between two",
  "북쪽": "a compass pointing north",
  "남쪽": "a compass pointing south",
  "동그라미": "a perfect round circle",
  "별모양": "a shiny yellow star shape",
  "하트": "a cute red heart",
  "다이아몬드": "a sparkling blue diamond shape",
  "줄무늬": "colorful horizontal stripes pattern",
  "물결무늬": "blue wavy lines pattern",
  "체크무늬": "a red checkered pattern",
  "점박이": "a fabric with polka dots",
  "콧구멍": "a small nose nostril",
  "귓볼": "a soft earlobe part",
  "손목": "a child's small wrist",
  "손바닥": "an open hand palm",
  "발바닥": "a cute bare foot sole",
  "엄지": "a big thumb finger",
  "검지": "a pointing finger",
  "약지": "a finger with a ring",
  "새끼손가락": "a tiny little finger",
  "베이지색": "a light brown color",
  "투명": "clear see-through glass",
  "무지개색": "bright colorful rainbow arc",
  "자정": "a dark starry night",
  "새벽": "a soft morning sunrise",
  "모레": "two suns on calendar",
  "그저께": "two moons on calendar",
  "일주일": "seven days on calendar",
  "한달": "a full moon calendar",
  "알록달록": "many bright colorful dots",
  "새콤달콤": "a lemon and candy",
  "달달하다": "a sweet candy treat",
  "멜론": "a round green melon",
  "코코넛": "a brown hairy coconut",
  "리치": "a small red lychee",
  "자두": "a round purple plum",
  "살구": "a small orange apricot",
  "모과": "a yellow bumpy quince",
  "고추": "a long red pepper",
  "피망": "a colorful bell pepper",
  "아스파라거스": "green asparagus stalks",
  "브로콜리": "a green broccoli tree",
  "셀러리": "a green celery stalk",
  "콩나물": "white bean sprouts",
  "두부": "a white soft tofu block",
  "생강": "a bumpy brown ginger root",
  "파": "a long green onion",
  "대파": "a long white green onion",
  "쪽파": "thin green chives",
  "다락방": "a cozy attic room",
  "지하실": "a dark underground room",
  "발코니": "a small outdoor balcony",
  "창고": "a small storage shed",
  "다용도실": "a room for laundry",
  "붙박이장": "a closet in the wall",
  "서랍장": "a chest of drawers",
  "옷걸이": "a clothes hanger hook",
  "빨래건조대": "a clothes drying rack",
  "오로라": "a colorful northern lights sky",
  "미세먼지": "tiny invisible dust particles",
  "서리": "white frost on leaves",
  "이슬": "tiny water drops on grass",
  "초원": "a wide green meadow",
  "툰드라": "a cold flat land",
  "맹그로브": "a tree in water",
  "산호초": "colorful underwater coral reef",
  "고속버스": "a big long bus",
  "시내버스": "a big city bus",
  "마을버스": "a small village bus",
  "급행열차": "a fast express train",
  "모노레일": "a sleek monorail train",
  "유람선": "a big cruise ship",
  "열기구": "a colorful hot air balloon",
  "글라이더": "a soaring glider plane",
  "경운기": "a small farm tractor",
  "분필": "colorful chalk sticks",
  "공책": "a blank paper notebook",
  "크레용": "bright wax crayons",
  "수학": "numbers and shapes",
  "과학": "a bubbling science experiment",
  "음악": "musical notes dancing",
  "체육": "a child playing sports",
  "외할머니": "a kind grandma smiling",
  "외할아버지": "a kind grandpa smiling",
  "친할머니": "a sweet grandma smiling",
  "친할아버지": "a sweet grandpa smiling",
  "외삼촌": "a friendly uncle waving",
  "이모": "a friendly aunt smiling",
  "고모": "a sweet aunt smiling",
  "삼촌": "a sweet uncle waving",
  "사촌": "two happy child cousins",
  "조카": "a cute baby smiling",
  "단짝": "two happy best friends",
  "이웃": "friendly neighbors waving",
  "오르간": "a grand pipe organ",
  "클라리넷": "a shiny black clarinet",
  "색소폰": "a golden saxophone instrument",
  "하프": "a beautiful golden harp",
  "콘트라베이스": "a big wooden double bass",
  "캐스터네츠": "clicking wooden castanets",
  "박자": "musical notes and a drum",
  "수채화": "a colorful watercolor painting",
  "유화": "a rich oil painting",
  "판화": "a printed art picture",
  "점토": "soft colorful clay",
  "콜라주": "a picture made of cutouts",
  "데칼코마니": "a symmetrical ink blot painting",
  "마블링": "swirly colorful marbled paper",
  "태양계": "planets orbiting the sun",
  "소행성": "a rocky asteroid floating",
  "블랙홀": "a swirling black hole",
  "성운": "a colorful space cloud",
  "위성": "a small orbiting satellite",
  "천체망원경": "a big space telescope",
  "북극성": "a bright shining north star",
  "금성": "the bright planet venus",
  "천왕성": "the blue planet uranus",
  "티라노사우루스": "a big green tyrannosaurus rex",
  "트리케라톱스": "a three-horned triceratops dinosaur",
  "브라키오사우루스": "a long-necked brachiosaurus dinosaur",
  "스테고사우루스": "a spiky-backed stegosaurus dinosaur",
  "익룡": "a flying pterodactyl dinosaur",
  "수장룡": "a long-necked plesiosaur swimming",
  "화석": "a dinosaur bone fossil",
  "공룡알": "a spotted dinosaur egg",
  "원피스": "a pretty pink dress",
  "점퍼": "a warm colorful jacket",
  "가디건": "a cozy knitted cardigan",
  "후드티": "a comfy hooded sweatshirt",
  "청바지": "blue denim jeans",
  "반바지": "a pair of shorts",
  "샌들": "colorful summer sandals",
  "장화": "bright yellow rain boots",
  "프라이팬": "a shiny cooking frying pan",
  "도마": "a wooden cutting board",
  "국자": "a silver soup ladle",
  "뒤집개": "a flat cooking spatula",
  "체": "a kitchen mesh sieve",
  "믹서기": "a tall kitchen blender",
  "오븐": "a warm kitchen oven",
  "식칼": "a small kitchen knife",
  "수저": "a spoon and chopsticks set",
  "접시": "a round dinner plate",
  "그릇": "a colorful empty bowl",
  "컵": "a clear drinking cup",
  "머그컵": "a cute patterned mug",
  "냄비받침": "a round pot holder",
  "생일파티": "a fun birthday party",
  "초대장": "a colorful party invitation",
  "포장지": "shiny gift wrapping paper",
  "폭죽": "colorful exploding fireworks",
  "축하": "a happy celebratory moment",
  "입학": "a child starting school",
  "발표회": "children performing on stage",
  "크리스마스": "a festive christmas tree",
  "마법봉": "a sparkling magic wand",
  "투명망토": "a shimmering invisibility cloak",
  "수정구슬": "a glowing crystal ball",
  "요술램프": "a golden magic lamp",
  "황금열쇠": "a shiny golden key",
  "마법약": "a bubbling magic potion",
  "저주": "a dark magic spell",
  "유니콘": "a magical white unicorn",
  "인어공주": "a beautiful mermaid princess",
  "피노키오": "a wooden puppet pinocchio",
  "빨간모자": "little red riding hood",
  "신데렐라": "cinderella in a ball gown",
  "백설공주": "snow white princess with apple",
  "판사": "a wise judge in a robe",
  "변호사": "a lawyer talking in court",
  "회계사": "a person counting money numbers",
  "프로그래머": "a person typing on computer",
  "디자이너": "a person drawing clothes designs",
  "영양사": "a person with healthy food",
  "사진사": "a person taking a photo",
  "마술사": "a magician with a magic wand",
  "환경미화원": "a person cleaning the street",
  "배우": "an actor on a stage",
  "가수": "a singer with a microphone",
  "댄서": "a person dancing happily",
  "만화가": "a person drawing a comic",
  "제빵사": "a baker making fresh bread",
  "재활용": "recycling bins for trash",
  "분리수거": "sorting trash into bins",
  "지구온난화": "a hot earth melting ice",
  "태양광": "sun shining on solar panels",
  "풍력": "wind blowing a turbine",
  "나무심기": "a child planting a tree",
  "텃밭": "a small garden with vegetables",
  "퇴비": "a pile of compost dirt",
  "절수": "a dripping faucet water saving",
  "탄소": "a black carbon atom molecule",
  "곱하기": "a cute bunny multiplying numbers",
  "나누기": "a cute bunny dividing numbers",
  "같다": "two identical happy faces",
  "다르다": "two different shaped objects",
  "청진기": "a doctor's stethoscope on chest",
  "붕대": "a white bandage on arm",
  "석고붕대": "a cast on a broken arm",
  "수술": "a doctor performing surgery carefully",
  "엑스레이": "an x-ray of bones",
  "응급실": "an emergency room sign",
  "입원": "a child in a hospital bed",
  "퇴원": "a child leaving the hospital",
  "처방전": "a doctor writing a prescription",
  "숨바꼭질": "children playing hide and seek",
  "술래잡기": "children playing tag running",
  "오징어게임": "children playing squid game",
  "달팽이게임": "children playing snail game",
  "무궁화꽃이피었습니다": "children playing red light green light",
  "가위바위보": "children playing rock paper scissors",
  "딱지치기": "children flipping paper tiles",
  "구슬치기": "children playing with marbles",
  "고무줄넘기": "children jumping over elastic rope",
  "체스": "a chessboard with pieces",
  "장기": "a janggi board with pieces",
  "바둑": "a baduk board with stones",
  "카드게임": "a fun card game",
  "단풍나무": "a red maple tree",
  "은행나무": "a yellow ginkgo tree",
  "수국": "a big blue hydrangea flower",
  "라일락": "a purple lilac flower",
  "제비꽃": "a small purple violet flower",
  "냉이": "a green shepherd's purse plant",
  "쑥": "a green mugwort plant",
  "부들": "a tall brown cattail plant",
  "수련": "a pink water lily flower",
  "연꽃": "a beautiful pink lotus flower",
  "싹": "a tiny green plant sprout",
  "줄기": "a long green plant stem",
  "꽃봉오리": "a small closed flower bud",
  "가랑비": "light gentle rain falling",
  "장마": "heavy summer rain falling",
  "폭염": "a very hot sunny day",
  "한파": "a very cold snowy day",
  "습도": "misty air in summer",
  "기온": "a thermometer showing warmth",
  "기압": "a weather barometer gauge",
  "무더위": "a hot sticky summer day",
  "꽃샘추위": "a chilly spring breeze",
  "온도": "a thermometer showing warmth",
  "기상예보": "a sun cloud weather forecast",
  "태풍경보": "a strong wind typhoon warning",
  "뛰어오르다": "a cute bunny jumping up",
  "구르다": "a cute puppy rolling around",
  "넘어지다": "a cute bear falling down",
  "기어가다": "a cute baby crawling slowly",
  "날아가다": "a cute bird flying away",
  "헤엄치다": "a cute fish swimming happily",
  "고개젓다": "a cute kitten shaking head",
  "손흔들다": "a cute child waving hand",
  "안아주다": "a cute bear hugging friend",
  "조금씩": "a tiny bit of something",
  "가득": "a cup filled to brim",
  "절반": "half of an apple",
  "처음": "a starting line first place",
  "나중": "a finish line later",
  "먼저": "a starting line first place",
  "천천히": "a cute snail moving slowly",
  "함께": "two friends holding hands",
  "향기롭다": "a sweet smelling flower",
  "신맛": "a puckered sour face",
  "쓴맛": "a grimacing bitter face",
  "매운맛": "a red hot spicy pepper",
  "삼각형": "a red triangle shape",
  "사각형": "a blue square shape",
  "원": "a yellow circle shape",
  "육각형": "a six-sided shape",
  "정육면체": "a six-sided box shape",
  "구형": "a round ball shape",
  "원기둥": "a round tube shape",
  "순서": "a line of cute animals",
  "단어": "a letter block",
  "사전": "a big book with words",
  "설거지": "a cute bear washing dishes",
  "장보기": "a cute squirrel shopping",
  "요리": "a cute fox cooking food",
  "다림질": "a cute cat ironing clothes",
  "정리": "a cute bunny tidying up",
  "쓸다": "a cute mouse sweeping floor",
  "닦다": "a cute puppy wiping table",
  "버리다": "a cute monkey throwing trash",
  "안전벨트": "a car seatbelt",
  "신호등": "a red green yellow light",
  "횡단보도": "white stripes on road",
  "안전모": "a yellow construction helmet",
  "구명조끼": "an orange life vest",
  "소화기": "a red fire extinguisher",
  "비상구": "a green exit sign",
  "규칙": "a cute animal following rules",
  "약속": "two cute animals shaking hands",
  "조심": "a cute animal being careful",
  "현미경": "a science microscope",
  "아파트": "a tall building with windows",
  "빌라": "a small fancy house",
  "단독주택": "a single family house",
  "난간": "a fence on stairs",
  "울타리": "a wooden garden fence",
  "지붕": "a red house roof",
  "굴뚝": "a house chimney with smoke",
  "댐": "a big water wall",
  "모래사장": "a yellow sandy beach",
  "소라": "a spiral seashell",
  "성게": "a spiky sea creature",
  "새우": "a pink curved shrimp",
  "낙지": "a small brown octopus",
  "오징어": "a white sea squid",
  "바닷속": "colorful fish underwater",
  "잠수": "a cute otter diving underwater",
  "스노클링": "a cute bear snorkeling",
  "농장": "a red barn farm",
  "논": "a green rice paddy field",
  "밭": "a brown vegetable field",
  "벼": "green rice plants",
  "트랙터": "a red farm tractor",
  "우물": "a stone water well",
  "초가집": "a traditional straw roof house",
  "닭장": "a small wooden chicken house",
  "외양간": "a big red barn building",
  "앗따": "a surprised wide-eyed face",
  "어머나": "a surprised wide-eyed face",
  "짝짝짝": "a cute bear clapping hands",
  "손가락질": "a cute bunny pointing a finger",
  "코풀기": "a cute elephant blowing its nose",
  "손톱깎기": "a cute cat clipping its nails",
  "머리감기": "a cute puppy washing its hair",
  "칫솔": "a small colorful toothbrush",
  "샴푸": "a bottle of bubbly shampoo",
  "린스": "a bottle of creamy conditioner",
  "손소독제": "a small bottle of hand sanitizer",
  "애니메이션": "a colorful cartoon movie scene",
  "영화": "a big movie screen",
  "유튜브": "a red youtube logo icon",
  "음악방송": "a cute animal singing on tv",
  "뉴스": "a television showing news",
  "콘서트": "a stage with bright lights",
  "뮤지컬": "a stage with singing actors",
  "연극": "actors performing on a stage",
  "마술공연": "a magician doing a magic trick",
  "쌍둥이": "two identical cute babies",
  "짬뽕": "a bowl of spicy noodles",
  "쭈꾸미": "a small webfoot octopus",
  "쪼그리다": "a cute frog squatting down",
  "뽑다": "a cute squirrel pulling a carrot",
  "찌르다": "a cute hedgehog poking something",
  "떨다": "a cute penguin shivering cold",
  "쏘다": "a cute bee stinging a flower",
  "삐다": "a cute puppy limping in pain",
  "따르릉": "a cute phone ringing loudly",
  "쨍그랑": "a cute glass breaking sound",
  "쏴아": "a cute whale splashing water",
  "뚝배기": "a small black earthenware pot",
  "쑤시다": "a cute bear poking with a stick",
  "꿰매다": "a cute mouse sewing clothes",
  "써레질": "a cute farmer harrowing a field",
  "뜯다": "a cute bunny tearing a leaf",
  "쫓다": "a cute dog chasing a ball",
  "찢다": "a cute kitten ripping paper",
  "깎다": "a cute monkey peeling a banana",
};
